/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Controlador.ControladorEjecucion;
import com.mycompany.proyectoso.ProyectoSO;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Daniel
 */
public class Ejecuciones extends javax.swing.JFrame {

    private int listadoId;
    private DefaultTableModel model = new DefaultTableModel();
    private String resultado;
    private ControladorEjecucion controlador;
    /**
     * Creates new form Ejecuciones
     */
    public Ejecuciones(ControladorEjecucion controlador) {
        initComponents();
        this.controlador = controlador;
        String[] Titulos = new String[]{"Ejecucion Id","Listado Id","Turnaround Time Prom","Response Time Prom","Algoritmo","Fecha","Hora"};
        this.model.setColumnIdentifiers(Titulos);
        this.jtEjecuciones.setModel(this.model);
        llenarTablaC(controlador.listarEjecucion());
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
 
    //METODOS DE LA CLASE
    void llenarTablaC(ResultSet listado) {
        jtEjecuciones.clearSelection();
        model.getDataVector().removeAllElements();
        try {
            while (listado.next()) {
                model.addRow(new Object[]{
                    (listado.getInt(1)),
                    (listado.getInt(2)),
                    (listado.getDouble(3)),
                    (listado.getDouble(4)),
                    listado.getString(5),
                    (listado.getDate(6)),
                    (listado.getTime(7))
                    });
            }
            jtEjecuciones.updateUI();
            
        } catch (SQLException ex) {
            System.out.println("EStoy aqui"+ex.getMessage());
        }
    }
    
    public void convertirResultados(ResultSet resultados){
     
        this.resultado = "------------------------RESULTADOS----------------------------------\n";
        
        try {
            while (resultados.next()) {
                    this.resultado += "Tiempo Llegada: " + String.valueOf(resultados.getDouble(3)) +"\n";
                    this.resultado += "Teimpo inicial" + String.valueOf(resultados.getDouble(5))+ "\n";
                    this.resultado += "Tiempo Final: " + String.valueOf(resultados.getDouble(3)) +"\n";
                    this.resultado += "Tiempo Estimado Ingresado: " + String.valueOf(resultados.getDouble(4)) + "\n";
                    this.resultado += "Turnaround Time: " + resultados.getDouble(7) + "\n";
                    this.resultado += "Response Time: " + String.valueOf(resultados.getDouble(6)) + "\n\n";

            }         
        } catch (SQLException ex) {
            System.out.println("EStoy aqui"+ex.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtEjecuciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtEjecuciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ejecucion id", "Listado Id", "Turnaround Time Prom", "Response Tiem Prom", "Algoritmo", "Fecha", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtEjecuciones);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Ejecuciones");

        jButton1.setText("Mostrar Ejecucion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbAtras.setText("Atras");
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAtras)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        ProyectoSO.Glistados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAtrasActionPerformed
    
    private void Closing(java.awt.event.WindowEvent evt) {                         
        controlador.detenerContenedor();
        System.exit(0);
    } 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int listado_id;
        int fila = jtEjecuciones.getSelectedRow();
        listado_id = (int)jtEjecuciones.getValueAt(fila,1);        
        convertirResultados(controlador.consultarResultados(listado_id));
        
        MostrarEjecucion mostrarEjecucion = new MostrarEjecucion(controlador);
        mostrarEjecucion.setVisible(true);
        mostrarEjecucion.setResultado(this.resultado);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtras;
    private javax.swing.JTable jtEjecuciones;
    // End of variables declaration//GEN-END:variables
}
